/*
 * Poster-owned media asset identity and lifecycle.
 *
 * assetId is intentionally opaque outside the Backend.
 *
 * Admin, Client, Website, Copyright, and Mobile must never:
 * - derive a storage object key from assetId;
 * - derive a bucket from assetId;
 * - manufacture a delivery URL from assetId.
 *
 * Storage location remains Backend-owned so bucket,
 * CDN, signing, and provider choices can change without
 * changing public application contracts.
 */

export const MEDIA_ASSET_PURPOSES = [
  "poster_promotion",
] as const;

export type MediaAssetPurpose =
  typeof MEDIA_ASSET_PURPOSES[number];

export const MEDIA_ASSET_MEDIA_TYPES = [
  "image",
  "video",
] as const;

export type MediaAssetMediaType =
  typeof MEDIA_ASSET_MEDIA_TYPES[number];

export const MEDIA_ASSET_STORAGE_PROVIDERS = [
  "gcs",
] as const;

export type MediaAssetStorageProvider =
  typeof MEDIA_ASSET_STORAGE_PROVIDERS[number];

export const MEDIA_ASSET_STATUSES = [
  "pending_upload",
  "ready",
  "failed",
  "deleted",
] as const;

export type MediaAssetStatus =
  typeof MEDIA_ASSET_STATUSES[number];

/*
 * Backend-only physical storage locator.
 *
 * This value is deliberately separate from the opaque
 * assetId exposed to business-domain records.
 */
export interface MediaAssetStorageLocator {
  provider:
    MediaAssetStorageProvider;

  bucket:
    string;

  objectKey:
    string;
}

/*
 * Stable metadata that business domains may reference
 * without knowing where or how the object is stored.
 */
export interface MediaAssetReference {
  assetId:
    string;

  mediaType:
    MediaAssetMediaType;

  fileName:
    string;

  mimeType:
    string;

  sizeBytes:
    number;
}

export interface MediaAssetRecord
  extends MediaAssetReference {
  purpose:
    MediaAssetPurpose;

  storage:
    MediaAssetStorageLocator;

  status:
    MediaAssetStatus;

  createdByUserId:
    string;

  createdAt:
    Date;

  updatedAt:
    Date;

  rowVersion:
    string;
}

/*
 * Repository creation input.
 *
 * assetId and physical storage identity are generated by
 * Backend application/storage logic before persistence.
 */
export interface CreateMediaAssetRecordInput
  extends MediaAssetReference {
  purpose:
    MediaAssetPurpose;

  storage:
    MediaAssetStorageLocator;

  status:
    MediaAssetStatus;

  createdByUserId:
    string;

  createdAt:
    Date;
}

export interface UpdateMediaAssetStatusInput {
  assetId:
    string;

  expectedRowVersion:
    string;

  status:
    MediaAssetStatus;
}

export type MediaAssetStatusUpdateResult =
  | {
      status:
        "updated";

      asset:
        MediaAssetRecord;
    }
  | {
      status:
        "conflict";

      current:
        MediaAssetRecord;
    }
  | {
      status:
        "not_found";
    };

export interface MediaAssetRepository {
  findById:
    (
      assetId:
        string,
      executor?:
        import("../../database/database.pool.js").DatabaseQueryExecutor
    ) =>
      Promise<
        MediaAssetRecord |
        null
      >;

  create:
    (
      input:
        CreateMediaAssetRecordInput,
      executor?:
        import("../../database/database.pool.js").DatabaseQueryExecutor
    ) =>
      Promise<
        MediaAssetRecord
      >;

  updateStatus:
    (
      input:
        UpdateMediaAssetStatusInput,
      executor?:
        import("../../database/database.pool.js").DatabaseQueryExecutor
    ) =>
      Promise<
        MediaAssetStatusUpdateResult
      >;
}

/*
 * Delivery URLs are intentionally absent from
 * MediaAssetRecord.
 *
 * Signed/public delivery URLs are runtime projections
 * produced by the Backend storage resolver and are not
 * persisted as the asset's stable identity.
 */
export interface MediaAssetDeliveryProjection
  extends MediaAssetReference {
  url:
    string;
}