-- Poster Brain persistent semantic content embeddings
-- Migration: 0028_poster_brain_content_embeddings
--
-- Embeddings remain attached to discovery content.
-- Backend/PostgreSQL owns persistence.
-- Python AI generates vectors but receives no direct DB access.

CREATE TABLE app.discovery_content_embeddings (
    id uuid PRIMARY KEY
        DEFAULT gen_random_uuid(),

    content_id uuid NOT NULL
        REFERENCES app.discovery_content_items(id)
        ON DELETE CASCADE,

    provider_name text NOT NULL,

    model_name text NOT NULL,

    dimensions integer NOT NULL
        DEFAULT 384,

    embedding double precision[] NOT NULL,

    generated_at timestamptz NOT NULL,

    created_at timestamptz NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    row_version bigint NOT NULL
        DEFAULT 1,

    CONSTRAINT discovery_content_embeddings_provider_not_blank
        CHECK (
            length(
                btrim(provider_name)
            ) >= 1
        ),

    CONSTRAINT discovery_content_embeddings_model_not_blank
        CHECK (
            length(
                btrim(model_name)
            ) >= 1
        ),

    CONSTRAINT discovery_content_embeddings_dimensions_384
        CHECK (
            dimensions = 384
        ),

    CONSTRAINT discovery_content_embeddings_vector_384
        CHECK (
            array_ndims(embedding) = 1
            AND cardinality(embedding) = 384
        ),

    CONSTRAINT discovery_content_embeddings_row_version_valid
        CHECK (
            row_version >= 1
        ),

    CONSTRAINT discovery_content_embeddings_content_model_unique
        UNIQUE (
            content_id,
            provider_name,
            model_name
        )
);

CREATE INDEX
    discovery_content_embeddings_model_idx
ON app.discovery_content_embeddings (
    provider_name,
    model_name,
    content_id
);

CREATE TRIGGER
    discovery_content_embeddings_set_updated_at_and_version
BEFORE UPDATE
ON app.discovery_content_embeddings
FOR EACH ROW
EXECUTE FUNCTION
    app.set_updated_at_and_version();

REVOKE ALL
ON app.discovery_content_embeddings
FROM PUBLIC;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE
ON app.discovery_content_embeddings
TO poster_app;

COMMENT ON TABLE
    app.discovery_content_embeddings
IS
    'Poster Brain semantic embeddings for discovery content. Current storage uses validated 384-dimensional dense arrays and exact cosine lookup.';

COMMENT ON COLUMN
    app.discovery_content_embeddings.embedding
IS
    'Normalized 384-dimensional dense semantic vector generated by the internal Poster Python AI embedding service.';